models/node.py
import hashlib
import os

from . import ModelMixin
from . import db


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    topics = db.relationship('Topic', backref='node')

    def __init__(self, form):
        self.name = form.get('name', '')

    def update(self, form):
        self.name = form.get('name', '')
        self.save()

models/topic.py
import hashlib
import os

from . import ModelMixin
from . import db


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    content = db.Column(db.String())
    description = db.Column(db.String())
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))

    def __init__(self, form):
        self.title = form.get('title', '')
        self.content = form.get('content', '')

    def update(self, form):
        self.content = form.get('content', '')
        self.save()

routes/comment.py
from models.comment import Comment
from routes import *


main = Blueprint('comment', __name__)

Model = Comment

#
# @main.route('/')
# def index():
#     ms = Model.query.all()
#     return render_template('topic_index.html', node_list=ms)


# @main.route('/new')
# def new():
#     return render_template('topic_new.html')


# @main.route('/<int:id>')
# def show(id):
#     m = Model.query.get(id)
#     return render_template('topic.html', topic=m)


# @main.route('/edit/<id>')
# def edit(id):
#     t = Model.query.get(id)
#     return render_template('topic_edit.html', todo=t)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.topic_id = int(form.get('topic_id'))
    m.save()
    return redirect(url_for('topic.show', id=m.topic_id))


# @main.route('/update/<int:id>', methods=['POST'])
# def update(id):
#     form = request.form
#     t = Model.query.get(id)
#     t.update(form)
#     return redirect(url_for('.index'))
#
#
# @main.route('/delete/<int:id>')
# def delete(id):
#     t = Model.query.get(id)
#     t.delete()
#     return redirect(url_for('.index'))

routes/node.py
from models.node import Node
from models.topic import Topic
from routes import *

from functools import wraps

main = Blueprint('node', __name__)

# pyid = id
Model = Node


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # your code
        print('admin required')
        if request.args.get('uid') != '1':
            print('not admin')
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('node_index.html', node_list=ms)


@main.route('/new')
def new():
    return render_template('node_new.html')


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    return render_template('node.html', node=m)


@main.route('/edit/<id>')
def edit(id):
    m = Model.query.get(id)
    return render_template('node_edit.html', node=m)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    # t = Todo.query.filter_by(id=id).first()
    m = Model.query.get(id)
    m.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
@admin_required
def delete(id):
    # Model.delete(id)
    m = Model.query.filter_by(id=id).first()
    m.delete()
    return redirect(url_for('.index'))

routes/topic.py
from models.topic import Topic
from routes import *


main = Blueprint('topic', __name__)

# pyid = id
Model = Topic


@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('topic_index.html', node_list=ms)


@main.route('/new')
def new():
    return render_template('topic_new.html')


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    return render_template('topic.html', topic=m)


@main.route('/edit/<id>')
def edit(id):
    m = Model.query.get(id)
    return render_template('topic_edit.html', node=m)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.node_id = int(form.get('node_id'))
    m.save()
    return redirect(url_for('node.show', id=m.node_id))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    # t = Todo.query.filter_by(id=id).first()
    m = Model.query.get(id)
    m.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
def delete(id):
    # Model.delete(id)
    m = Model.query.filter_by(id=id).first()
    m.delete()
    return redirect(url_for('.index'))

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bbs.css') }}">
    {% block css %}{% endblock %}

    <script src="/static/js/jquery-3.0.0.min.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
    <div class="bbs-top">
        <a href="/node/1">主页</a>
        <nav class="bbs-menu">
            <a class="gua-nav-link gua-active" href="/">首页</a>
            <a class="gua-nav-link" href="/topics/333">注册</a>
            <a class="gua-nav-link" href="/topics/310">登录</a>
        </nav>
    </div>
    <div class="bbs-main">
        <div class="bbs-content bbs-box">
            {% block content %}
            {% endblock %}
        </div>
        <div class="bbs-sidebar bbs-box">
            <a href="/topic/new">发布新帖子</a>
            {% block sidebar %}
            {% endblock %}
        </div>
    </div>

    <div class="bbs-bottom">
        <div class="bbs-bottom-content bbs-content-size">
            <div class="bbs-bottom-nav">
                <a href="#">关于</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">FAQ</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">鸣谢</a>
                <span>&nbsp;·&nbsp;</span>
                <a href="#">7人在线</a>
            </div>
            <div class="bbs-bottom-about">
                创意工作者们的社区<br>World is powered by solitude
            </div>
        </div>
    </div>
</body>
</html>

templates/node.html
{% extends "base.html" %}

{% block title %}
    发帖
{% endblock %}

{% block content %}
    {% for t in node.topics %}
    <div>
        <a href="{{ url_for('topic.show', id=t.id) }}">
            {{ t.title }}
        </a>
    </div>
    {% endfor %}
{% endblock %}

templates/node_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>node edit</title>
</head>
<body>
    <div>
        <form action="{{ url_for('.update', id=node.id) }}" method="post">
            <input type="text" name="name" value="{{ node.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/node_index.html
{% extends "base.html" %}

{% block title %}
    nodes
{% endblock %}

{% block content %}
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="name" placeholder="输入 name">
            <br>
            <input type="text" name="description" placeholder="输入 description">
            <br>
            <button>Add</button>
        </form>
    </div>

    {% for node in node_list %}
    <div>
        {{ node.id }} : {{ node.name }}
    </div>
    {% endfor %}
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">发布新帖子</a>
{% endblock %}

templates/node_new.html
{% extends "base.html" %}

{% block title %}
    发帖
{% endblock %}

{% block content %}
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="title" placeholder="输入 title">
        <textarea name="content" placeholder="输入 content"></textarea>
        <button>Add</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">发布新帖子</a>
{% endblock %}

templates/todo_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo edit</title>
</head>
<body>
    <div>
        <form action="{{ url_for('.update', id=todo.id) }}" method="post">
            <input type="text" name="task" value="{{ todo.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/todo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo</title>
    <style>
        form {
            display: inline-block;
        }
    </style>
</head>
<body>
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <input type="text" name="task" placeholder="输入 todo">
            <button>Add</button>
        </form>
    </div>

{% for todo in todo_list %}
    <div>
        <a href="{{ url_for('.edit', id=todo.id) }}">修改</a>
        <a href="{{ url_for('.delete', id=todo.id) }}">删除</a>
        {{ todo.task }}
    </div>
{% endfor %}

</body>
</html>

templates/topic.html
{% extends "base.html" %}

{% block title %}
    {{ topic.title }}
{% endblock %}

{% block content %}
    <div class="">
        <a href="{{url_for('node.show', id=topic.node.id)}}">{{ topic.node.name }}</a>
    </div>
    <div>
        <h1>{{ topic.title }}</h1>
        <p>
            {{ topic.content}}
        </p>
    </div>

    <div class="bbs-comments">
        {% for c in topic.comments %}
        <div>
            {{ c.content }}
        </div>
        {% endfor %}
    </div>

    <div>
        <form action="{{ url_for('comment.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>发表回复</button>
        </form>
    </div>
{% endblock %}

templates/topic_index.html
{% extends "base.html" %}

{% block title %}
    nodes
{% endblock %}

{% block content %}
    <h1>content</h1>
{% endblock %}

{% block sidebar %}
    <h1>hello </h1>
{% endblock %}

templates/topic_new.html
{% extends "base.html" %}

{% block title %}
    发帖
{% endblock %}

{% block content %}
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="node_id" placeholder="输入 node id">
        <br>
        <input type="text" name="title" placeholder="输入 title">
        <br>
        <textarea name="content" placeholder="输入 content"></textarea>
        <br>
        <button>Add</button>
    </form>
{% endblock %}


{% block sidebar %}
    <h1>hello </h1>
    <a href="/node/new">发布新帖子</a>
{% endblock %}